export {default as Navbar} from './navbar/Navbar'
export {default as  Home} from './Home/Home'
export {default as Statistics} from './statistics'
export { default as Contract} from './Contract'
export {default as Building} from './Building'
export {default as Bussiness} from './Busssiness'